### ISSUE TITLE
Env file doesn't install Altair-ally

### ISSUE THREAD

**Issue by jinxyou** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#20]
By running the conda-lock file, I'm unable to run the ipynb file without error since it doesn't install altair-ally. Additional steps have to be taken by typing `pip install altair-ally`, as this cannot be done through conda command.

**Comment by vrudhgarg** [comment]
That's interesting.  It looks like i have missed it. Can you please comment the code out for altair_ally and create a PR?

**Comment by shawnhu444** [comment]
yeah looks good merged it

**Comment by fishydays** [comment]
I tried to run `pip install altair-ally` in the environment that is created by the conda lock file, but it runs into an error because pip is not installed in it. We will need to update the conda lock file also for this to work.

**Comment by vrudhgarg** [comment]
I used this command (conda env export --from-history > environment.yml) from the lecture notes to create the yml file but for some reason it does not include the packages installed through pip.

**Comment by vrudhgarg** [comment]
We have added pip and altair_ally dependency. Closing this issue. @jinxyou @shawnhu444 @fishydays  @Lukman-Lateef
