### ISSUE TITLE
By using Docker-compose up, "deepchecks" and "Altair-ally" are not installed in the environment

### ISSUE THREAD

**Issue by jinxyou** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#42]
I followed the README, and type `docker-compose up`. Jupyter lab would pop up with an error stating that the environment does not have `deepchecks`, and `Altair-ally` installed. Even though the yml file has them listed, it seems like docker command does not necessarily install them.

**Comment by fishydays** [comment]
Can confirm this is an issue when I try it also. I think we need to update the docker file to have `RUN pip install deepchecks==0.18.1` and `RUN pip install altair-ally==0.1.1` for it to work

**Comment by jinxyou** [comment]
> Can confirm this is an issue when I try it also. I think we need to update the docker file to have `RUN pip install deepchecks==0.18.1` and `RUN pip install altair-ally==0.1.1` for it to work

Got it. I'm working on it

**Comment by vrudhgarg** [comment]
Issue was due to usage of the old docker file. Fixed and changes merged. Closing this issue
