### ISSUE TITLE
Reproducing Report

### ISSUE THREAD

**Issue by Lukman-Lateef** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#62]
Hi guys,

I ran into several issues while recreating the report using the `README.md` instructions from start on my local, I made some little changes that helped 
- made the path to `conda-lock.yml` file relative. 
- removed the raw file from the base data folder
- changed the raw data download path on the notebook to point to `../data/raw`

There are issues running the modularized scripts too, but will check further and report here.

**Comment by vrudhgarg** [comment]
Interesting, Thanks for all the hard work!

**Comment by shawnhu444** [comment]
Thanks! Looks good!
