### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by fishydays** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#66]
Hi guys,
The `ReadMe`  so far only has instructions for running the scripts, we need to update it to include the bash commands for rendering the quarto documents. Also, I don't think we should include the environment instructions for conda-lock anymore, just the instructions for docker should be enough.

**Comment by vrudhgarg** [comment]
Yes I removed the environment instructions from the repo so we are good on that part.
Also, can you check whether scripts are working correctly on your side?

**Comment by fishydays** [comment]
The script is working fine on my side, but noticed that we are still missing quarto in our docker image, created a seperate issue for this #70

**Comment by vrudhgarg** [comment]
Yep saw it and looks fine to me! @fishydays Can you close this issue?
