### ISSUE TITLE
Tasks based on reviewer comments

### ISSUE THREAD

**Issue by fishydays** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#92]
- [x] Add hyperlink to figures and tables in text @Lukman-Lateef 
- [x] Remove figure 2,3,6 @Lukman-Lateef 
- [x] Add brief text under each figure in EDA (can be rewording of what is currently in the results part) @Lukman-Lateef 
- [x] Fix grammatical errors @Lukman-Lateef @fishydays 
For example:
Original: "we developed compared two regression model."
Suggested: "We developed and compared two regression models."
- [ ] Review scripts and remove unneccsary codes @fishydays

**Comment by vrudhgarg** [comment]
Hey Guys. It looks like everyone needs to make some changes(as per the guideline in milestone 4) from peer review. I am removing figures 2,3,6 from quarto.

**Comment by vrudhgarg** [comment]
@Lukman-Lateef I commented out the  figure 2,3 and 6. Although, I need to add that into my CHANGELOG.md
